linters-settings:
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  govet:
    check-shadowing: false
  revive:
    rules:
      - name: unexported-return
        disabled: true
  nolintlint:
    require-explanation: true
    require-specific: true
  goimports:
    local-prefixes: github.com/irbgeo/usdt-rate

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - copyloopvar
    - goconst
    - gofmt
    - goimports
    - gocyclo
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - prealloc
    - predeclared
    - revive
    # - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - whitespace

run:
  issues-exit-code: 1
