// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	controller "github.com/irbgeo/usdt-rate/internal/controller"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Metrics is an autogenerated mock type for the metrics type
type Metrics struct {
	mock.Mock
}

// ObserveControllerRate provides a mock function with given fields: in, duration, err
func (_m *Metrics) ObserveControllerRate(in controller.Pair, duration time.Duration, err error) {
	_m.Called(in, duration, err)
}

// NewMetrics creates a new instance of Metrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *Metrics {
	mock := &Metrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
